name: Build and deploy gh-pages

on:
  push:
    branches:
      - relayer-dashboard

jobs:
  build_deploy_gh_page:
    name: Build and Deploy Github Page
    runs-on: ubuntu-latest
    steps:
      - name: Check out repos relayer-dashboard branch
        uses: actions/checkout@v3
        with:
          ref: "relayer-dashboard"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build and Deploy Github Page
        run: |
          yarn install
          NODE_ENV=production yarn build
          cp ./CNAME ./dist/
          cp ./robots.txt ./dist/

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          yarn dlx push-dir --dir=dist --branch=gh-pages --cleanup --verbose
